# Generated by Django 3.2.3 on 2021-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('RED', '#E06C75'), ('YELLOW', '#E5C07B'), ('GREEN', '#98C379'), ('BLUE', '#61AFEF'), ('DEFAULT', '#ECECEC')], default='DEFAULT', max_length=20),
        ),
    ]
